/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(add_usrp_tags.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(719ce4ec1b435387b5ea29dfa107d7b9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/iridiumtx/add_usrp_tags.h>
// pydoc.h is automatically generated in the build directory
#include <add_usrp_tags_pydoc.h>

void bind_add_usrp_tags(py::module& m)
{

    using add_usrp_tags = ::gr::iridiumtx::add_usrp_tags;


    py::class_<add_usrp_tags,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<add_usrp_tags>>(m, "add_usrp_tags", D(add_usrp_tags))

        .def(py::init(&add_usrp_tags::make),
             py::arg("sps") = 40,
             py::arg("current_time") = 1744444,
             py::arg("preamble_len") = 16,
             py::arg("padding_len") = 100,
             D(add_usrp_tags, make))


        .def("set_preamble_len",
             &add_usrp_tags::set_preamble_len,
             py::arg("preamble_len"),
             D(add_usrp_tags, set_preamble_len))

        ;
}
