/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(freq_shift.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5d19430d2a2fd2dd0b1ee9c6402f3ca4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/iridiumtx/freq_shift.h>
// pydoc.h is automatically generated in the build directory
#include <freq_shift_pydoc.h>

void bind_freq_shift(py::module& m)
{

    using freq_shift    = gr::iridiumtx::freq_shift;


    py::class_<freq_shift, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<freq_shift>>(m, "freq_shift", D(freq_shift))

        .def(py::init(&freq_shift::make),
           D(freq_shift,make)
        )
        



        ;




}








