/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(insert_delay.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(cc70821f10bcd104bf1077736aa5acf4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/iridiumtx/insert_delay.h>
// pydoc.h is automatically generated in the build directory
#include <insert_delay_pydoc.h>

void bind_insert_delay(py::module& m)
{

    using insert_delay    = gr::iridiumtx::insert_delay;


    py::class_<insert_delay, gr::block, gr::basic_block,
        std::shared_ptr<insert_delay>>(m, "insert_delay", D(insert_delay))

        .def(py::init(&insert_delay::make),
           D(insert_delay,make)
        )
        



        ;




}








